### PR TITLE
To Do list: list structure

### PR DESCRIPTION
**Pull request by myaserkhan**
- [ ] Set up a new project with webpack.
- [ ] The index.html file set as a template using the HTML Webpack Plugin.
- [ ] Created a style.css and set rules for the To Do List loaded by Webpack Style/CSS Loader.
- [ ] On page load render the dynamically created list of tasks in the dedicated placeholder.

### CODE REVIEW

**Review by ichala — CHANGES_REQUESTED** [review]
Hi @MYaserKhan, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

🛑 **_You have submitted a project, that includes future milestones that you are not required to do yet, since the task for this milestone cannot be identified and reviewed properly as well it can cause you some issues in your future milestones, kindly try to submit a pull request that **only** meets this milestone [requirements](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/m1_list_structure.md) , thank you_**

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by myaserkhan** [comment]
@ichala can you specify which milestone?

**Comment by ichala** [comment]
> @ichala can you specify which milestone?

 @MYaserKhan [To Do list: list structure](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/m1_list_structure.md), and as I sent you a message on slack try to only t work on this milestone and kindly update your readme file with the correct information since its another reason to invalidate

**Review by MaganaAsiati — APPROVED** [review]
# Status: Approved [✔️](https://emojipedia.org/check-mark/)
## Hi @MYaserKhan    , I'm @MaganaAsiati , your reviewer for this PR  :wave: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


clap

## Highlights
- descriptive README file  :heavy_check_mark:👨🏻‍💻
- Your commits should start with a capital letter :heavy_check_mark:👨🏻‍💻


## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [x] [OPTIONAL] Please make sure to make your commit messages more descriptive in the future.
- [x] kindly  Add a descriptive description in your pull request in future which give more information about what you implement in this milestone :heavy_check_mark:👨🏻‍💻


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Cheers and Happy coding!👏👏👏

**Pull request merged**
